# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Drew Goodin
email: dkg@fastmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Drew Goodin Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  drewgoodin

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

plugins:
    - jekyll-feed
    - jekyll-include-cache

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      # comments: true
      share: true
      related: false

author:
  name: "Drew G."
  avatar: "/assets/images/bio-photo.jpg"
  bio: "**CEO** (of this site)" # Note: Markdown is allowed
  location: "SF Bay Area"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-link"
      url: "mailto:dkg@fastmail.com"
      #- label: "GitHub"
      #  icon: "fab fa-fw fa-github"
      #  url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/goodin.drew"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/drewgoodin/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#

#repository:  "drewgoodin/drewgoodin.github.io"
#comments:
#  provider: "staticman_v2"
#  staticman:
#    branch: "master"
#    endpoint: "https://staticman.thewindowtailor.com/v3/entry/github/"
